### ISSUE TITLE
Removing OpenAI's package

### ISSUE THREAD

**Issue by fivepixels** [fivepixels/the-third-eye#2]
<img width="1800" alt="Screenshot 2024-03-06 at 08 29 04" src="https://github.com/cattynip/the-third-eye/assets/96553411/59a698be-0582-4360-972a-53e3383a4a35">

The image above shows what files or packages are compiled into the real resource, which the user will be directly using. As you can see, the `node_modules/openai` package takes up most of the space of the whole system, which means if that package can be removed and replaced by something vanilla javascript codes, the program will be way lighter and perform even better.

**Comment by cattynip** [comment]
That takes up 273KB...

**Comment by fivepixels** [comment]
<img width="1352" alt="Screenshot 2024-04-10 at 11 02 40 AM" src="https://github.com/fivepixels/the-third-eye/assets/96553411/ac046635-5b6a-4d0d-aed7-ee688d9f2ee2">

Before removing the OpenAI package, the total `dist` file's weight became *68KB*, which is significant and important since even though removing a lot of files and packages, it still works exactly the same and has lost a lot of weight.
